# Better leader
unbind C-b
set -g prefix C-s

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded Config"

# kill session
unbind K
bind K confirm kill-session

# Mouse
set -g mouse on

# Act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Reasonable pane management
unbind s
unbind v
unbind % # Split horizontal
unbind '"' # Split verticle 
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

unbind x
bind x kill-pane # kill pane without confirm
unbind k
bind k confirm kill-window # kill window with confirm

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Themes
%if #{==:#{THEME},LIGHT}
    base="#faf4ed";
    surface="#fffaf3";
    overlay="#f2e9e1";
    muted="#9893a5";
    subtle="#797593";
    text="#575279";
    love="#b4367a";
    gold="#ea9d34";
    rose="#d7827e";
    pine="#286983";
    foam="#56949f";
    iris="#907aa9";
    hl_low="#f4ede8";
    hl_med="#dfdad9";
    hl_high="#cecacd";
%else
    base="#191724";
    surface="#1f1d2e";
    overlay="#26233a";
    muted="#6e6a86";
    subtle="#908caa";
    text="#e0def4";
    love="#eb6f92";
    gold="#f6c177";
    rose="#ebbcba";
    pine="#31748f";
    foam="#9ccfd8";
    iris="#c4a7e7";
    hl_low="#21202e";
    hl_med="#403d52";
    hl_high="#524f67";
%endif

set -g status-position "top"
set -g status-justify "left"

set -g status-right "#[fg=$base,bg=$rose] %d/%m #[fg=$base,bg=$love] %H:%M:%S "
set -g status-right-length "50"
set -g status-left-length "20"
setw -g status-style "fg=$iris,bg=$base,bold"

setw -g window-status-current-style "fg=$love,bg=$surface"
setw -g window-status-current-format "#[fg=$love,bg=$surface] #I: #W "

setw -g window-status-style "fg=$rose,bg=$surface"
setw -g window-status-format "#[fg=$rose,bg=$surface] #I: #W "

# Pane
set -g pane-border-style "fg=$hl_low"
set -g pane-active-border-style "fg=$hl_high"
set -g display-panes-colour "$text"
set -g display-panes-active-colour "$gold"

# Message
set -g message-style "fg=$base,bg=$gold"
set -g message-command-style "fg=$base,bg=$gold"
